spring.application.name=DropTheLink
spring.datasource.url=jdbc:mysql://mysql-db:3306/drop_the_link_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION:1800000}