INSERT INTO users (username, email, password, role) VALUES
('niae', 'niaofnarnia@example.com', '$2a$12$RPJb4Q6V/QBg0ptyWPQLOuvTY.FDpLaT3NAAEFKA2BKmyupbiP9My', 'USER'),
('goddessbless', 'blessed@example.com', '$2a$12$RPJb4Q6V/QBg0ptyWPQLOuvTY.FDpLaT3NAAEFKA2BKmyupbiP9My', 'USER'),
('livinlikenah', 'yes.and@example.com', '$2a$12$RPJb4Q6V/QBg0ptyWPQLOuvTY.FDpLaT3NAAEFKA2BKmyupbiP9My', 'USER'),
('catlover', 'kitty@example.com', '$2a$12$RPJb4Q6V/QBg0ptyWPQLOuvTY.FDpLaT3NAAEFKA2BKmyupbiP9My', 'USER'),
('nunya', 'mind_ya@example.com', '$2a$12$RPJb4Q6V/QBg0ptyWPQLOuvTY.FDpLaT3NAAEFKA2BKmyupbiP9My', 'USER');

INSERT INTO playlists (name, description, is_published, user_id) VALUES
('My Favorites', 'Collection of some of my all time favorite songs', true, 1),
('Chill Vibes', 'Perfect for chilling', true, 2),
('Workout Mix', 'Pumping beats at the gym', false, 3),
('Guitar heavy', 'Some metal/rock songs that I like', true, 4),
('Video-Game music', 'Fun to listen to while studying', false, 5);

INSERT INTO videos (title, video_url) VALUES
('Harvest Moon DS Soundtrack', 'https://www.youtube.com/watch?v=8dKV_fyaH-8'),
('Harvest Moon - Friends of Mineral Town | Full OST','https://youtu.be/o54DvLchTPY'),
('Full Bomberman Hero OST', 'https://youtu.be/HQ-DJd-57Lo'),
('Zelda: Ocarina of Time - The Full Original Soundtrack OST', 'https://youtu.be/sIiEi96USlo'),
('Zelda: Majora`s Mask - Full OST', 'https://youtu.be/gzFQjMYmVyE'),
('Crumb - Ghostride', 'https://youtu.be/HS4aJ_51qNQ'),
('Gorillaz - Empire Ants ft. Little Dragon', 'https://youtu.be/C-yP9f0gadU'),
('Swindle - WHAT MORE (feat. Greentea Peng)', 'https://youtu.be/m8j7sw8ez8Y'),
('Little Dragon - High', 'https://youtu.be/-AsLISPht_M'),
('Kokoroko - ABUSEY JUNCTION', 'https://youtu.be/tSv04ylc6To'),
('Boris Brejcha - Good Vibes Only', 'https://youtu.be/S8BgEQQWpQA'),
('Boris Brejcha - Down Low', 'https://youtu.be/9UCyHa2-tQc'),
('Martin Kinrus - Revolt (Christian Craken Remix)', 'https://youtu.be/Esl8lL7Gvp4'),
('Oliver Huntemann - Tranquilizer (Christian Craken Remix)', 'https://youtu.be/MZOKkTLw-Ys'),
('Boris Brejcha - Thunderstorm', 'https://youtu.be/EEdpwswdpS0'),
('JINJER - Pisces (Live Session)', 'https://youtu.be/SQNtGoM3FVU'),
('Rammstein - Morgenstern', 'https://youtu.be/pFBgHMbrQK4'),
('Disturbed - Down With The Sickness', 'https://youtu.be/09LTT0xwdfw'),
('Rage Against The Machine - Killing In the Name', 'https://youtu.be/bWXazVhlyxQ'),
('Korn - Somebody Someone', 'https://youtu.be/FBEE-t-uyI0'),
('Weyes Blood - Andromeda', 'https://youtu.be/ZHGw78IJryE'),
('POLO & PAN — Pareidolies', 'https://youtu.be/xi2ZnQqYijM'),
('Mac Miller - Blue World', 'https://youtu.be/_GC2wFTCAGY'),
('Portishead - Revenge Of The Number', 'https://youtu.be/LXsvIjiST7E'),
('The Marías - Cariño', 'https://youtu.be/QHVp9xiUr9U');

INSERT INTO playlist_video (playlist_id, video_id, position) VALUES
(1, 25, 3),
(1, 24, 1),
(1, 23, 4),
(1, 22, 5),
(1, 21, 2),
(2, 6, 1),
(2, 7, 2),
(2, 8, 4),
(2, 9, 3),
(2, 10, 5),
(3, 11, 2),
(3, 12, 3),
(3, 13, 4),
(3, 14, 5),
(3, 15, 1),
(4, 20, 5),
(4, 19, 4),
(4, 18, 1),
(4, 17, 3),
(4, 16, 2),
(5, 1, 1),
(5, 2, 2),
(5, 3, 3),
(5, 4, 4),
(5, 5, 5);